### ISSUE TITLE
how to build this on Windows as x64

### ISSUE THREAD

**Issue by liuziangexit** [libexif/libexif#1]
i successfully build this to x86 binarys in Windows , use MinGW32.
but i want to know how to build this as x64...i mean, how to build 64bit version of libexif.lib、libexif-12.dll...
if you already have those 64bit binary, please give me a link.

thank you!

**Comment by dfandrich** [comment]
I personally haven't done this, but you should just be able to install the 64 bit version of the MinGW compilers and compile the same way using that compiler. Any further questions would be better off asked on the mailing list.

**Comment by liuziangexit** [comment]
thx

**Comment by liuziangexit** [comment]
I use CMake GUI to generate Visual Studio Solution, and then use Visual
Studio directly build it.

This project has lots of changes after early this year, so im not sure this
still work, but i think it probably might be...If you meet any problem,
just reply me here

**Comment by richipower** [comment]
Hey thanks for the reply, i wanted to build it with CMake GUI but there are no CMakeLists present.. (?)

**Comment by liuziangexit** [comment]
@richipower oh im so sorry, my last reply is not right, i was thought this is an issue from nokiatech/heif...

back to this issue, i remember i didn't sovle this build problem, and finally i switch to another exif library https://github.com/mayanklahiri/easyexif

**Comment by dfandrich** [comment]
FWIW, I just added an msys2 Appveyor build to the existing cygwin ones:
https://github.com/libexif/libexif/commit/bd58d1b056858b2c4c99d0845439c239424ca7c0
(see https://ci.appveyor.com/project/dfandrich/libexif) It just worked.
