### ISSUE TITLE
Need a new release

### ISSUE THREAD

**Issue by rossburton** [libexif/libexif#12]
There have been several security issues of late but the last release was years ago.  Can you make a new release?

**Comment by dfandrich** [comment]
There are a couple more security issues I'm sorting through first, but yes, a
release is definitely overdue.

**Comment by Neustradamus** [comment]
+1

**Comment by rossburton** [comment]
Please?

**Comment by hughmcmaster** [comment]
@dfandrich When do you think you will be able to release a new version of libexif?

**Comment by ptsneves** [comment]
What i have done is use the latest master of a point in time and freeze the hash on my recipes. But yeah..a bit overdue :)

**Comment by Neustradamus** [comment]
Very old: https://github.com/libexif/libexif/releases

**Comment by dfandrich** [comment]
I'm going to aim to get one out by the end of the month.

**Comment by sebastian-luna-valero** [comment]
+1

**Comment by Neustradamus** [comment]
Any news?

**Comment by hughmcmaster** [comment]
@dfandrich, do you expect to release a new version of libexif before the end of the year?

**Comment by hughmcmaster** [comment]
Hi Dan, any news on the timeline for a new release?

**Comment by mika** [comment]
Hello from 2020, is there anything we could help to see a new release of libexif?
Thanks and cheers!

**Comment by dfandrich** [comment]
The biggest blocker right now is triaging some security issues & filing for
CVEs as necessary. If someone from a distro security team or libexif packager
were willing to help with that, it would definitely speed things up.

**Comment by hughmcmaster** [comment]
@dfandrich, as one of the Debian maintainers, I can ask our security team to file CVEs if you can identify the vulnerabilities.

**Comment by msmeissn** [comment]
I think I went through over all open issues and solved them now.
Currently fuzzing has no open issues as far as I see.

**Comment by carnil** [comment]
@fandrich, @msmeissn, could you request CVEs as needed for the ones which doe not yet have a CVE assigned via https://cveform.mitre.org/ ?

**Comment by msmeissn** [comment]
I will try to get CVEs assigned and associated correctly.

**Comment by anthraxx** [comment]
@dfandrich any news? would be great to get a release that includes security fixes

**Comment by dfandrich** [comment]
Marcus has just pushed a bunch of fixes. A new release should happen Real Soon
Now.

**Comment by Neustradamus** [comment]
@msmeissn: Thanks a lot for this new release after 8 years!
- https://github.com/libexif/libexif/releases/tag/libexif-0_6_22-release
