### ISSUE TITLE
Can't Get Width and Height info 

### ISSUE THREAD

**Issue by Jason-YJ** [libexif/libexif#178]
I can't parse width and height exif info from a jpeg or jfif file from this:
```
exifData_ = std::shared_ptr<ExifData>(exif_data_new_from_file(url.Str().c_str()));
if (exifData_ == nullptr) {
    LOG(ERROR) << "ExifXmpData Construction(url) Failed! Error open Image file";
    parseResult = false;
}
ExifEntry *widthentry = exif_data_get_entry(exifData_, EXIF_TAG_IMAGE_WIDTH);
if (!widthentry) {
    LOG(WARNING) << "Exif Init Width Failed! Can't find tag 'EXIF_TAG_IMAGE_WIDTH'";
}
else {
    width_ = (int)(*(widthentry->data));
}
ExifEntry *heightentry = exif_data_get_entry(exifData_, EXIF_TAG_IMAGE_LENGTH);
if (!heightentry) {
    LOG(WARNING) << "Exif Init Height Failed! Can't find tag 'EXIF_TAG_IMAGE_LENGTH'";
}
else {
    height_ = (int)(*(heightentry->data));
}
```
I've tried several files, none of them can get this info while other tools like exiv2 or exiftool can.

**Comment by msmeissn** [comment]
can you attach a sample file?
and perhaps a compilable reproducer?

**Comment by Jason-YJ** [comment]
> can you attach a sample file? and perhaps a compilable reproducer?
I use the sample image from "https://www.fujifilm.com.hk/m/products/digital_cameras/x/fujifilm_x_a2/sample_images/" ( It seems jfif is not supported to be upload in github).
I've also test some custom format file based on jpg format.

**Comment by Jason-YJ** [comment]
> can you attach a sample file? and perhaps a compilable reproducer?

I solved it! I found the width/height info is recorded in "EXIF_TAG_PIXEL_X_DIMENSION/EXIF_TAG_PIXEL_Y_DIMENSION" rather than "EXIF_TAG_IMAGE_WIDTH/EXIF_TAG_IMAGE_LENGTH"

Anyway, thanks for reply

**Comment by msmeissn** [comment]
ah good to hear, thanks!
