### ISSUE TITLE
Document buffer's NUL terminated

### ISSUE THREAD

**Issue by jonnygrant** [libexif/libexif#18]
Noticed reading that 
`exif_entry_get_value` does not document that buffer returned is always NUL terminated

https://libexif.github.io/internals/exif-entry_8c.html

Perhaps others function APIs have this missing, could they all be clarified that they are NUL terminated please.

**Comment by dfandrich** [comment]
A few of the other functions e.g. exif_mnote_data_get_value, have pretty weak guarantees in this area and should really be improved.

**Comment by jonnygrant** [comment]
Hi

https://libexif.github.io/internals/exif-entry_8c.html

Looks to be the same.

**Comment by dfandrich** [comment]
The docs have to be manually rebuilt and uploaded. I've done so now.

**Comment by jonnygrant** [comment]
Thank you

exif_entry_get_value
maxlen	length of the buffer val
^ Is this accurate?
Before it seemed to exclude the NUL terminator...

BTW, exif_entry_format_value does not mention NUL-terminator

are there others?

**Comment by dfandrich** [comment]
What do you mean "before"? The function has always worked this way to my
knowledge. exif_entry_format_value is an internal function which is why it's
missing documentation, but it works the same way.

**Comment by jonnygrant** [comment]
Hi,
Quoting again:

exif_entry_format_value
val buffer in which to store value
[in] maxlen **one less than the length of the buffer val**


The manual appears to have been updated since I raised this issue, it doesn't state this anymore :-

https://libexif.github.io/internals/exif-entry_8c.html#ae02e9d58318a3cd50eb6730b5e657e5a

_It now states:_

static void exif_entry_format_value(ExifEntry * e,char * val,size_t maxlen ) | static void exif_entry_format_value | ( | ExifEntry * | e, |   |   | char * | val, |   |   | size_t | maxlen |   | ) |   |   | static
[in] | e | EXIF entry

[out] | val | buffer in which to store value
[in] | maxlen | **the length of the buffer val**

**Comment by dfandrich** [comment]
Please look at the current code in git. This is an outdated comment.

**Comment by jonnygrant** [comment]
Feels like a disingenuous reply.

You correct the defects, and then say my comment is out of date, and you don't even share your commit.

I won't comment further further messages, you're just wasting our time. 

Please refer to past messages, and I hope you will reflect on them.

**Comment by dfandrich** [comment]
I'm not sure what defects you're talking about, but all the commits are shared
with you at https://github.com/libexif/libexif/
