### ISSUE TITLE
exif_entry_format_value maxlen

### ISSUE THREAD

**Issue by jonnygrant** [libexif/libexif#19]
Hello

Couldn't help but notice the 'maxlen' parameter goes against regular POSIX API design and does not include the NUL terminating byte

http://man7.org/linux/man-pages/man3/strcpy.3.html

exif_entry_format_value
	val 	buffer in which to store value
[in] 	maxlen 	one less than the length of the buffer val

Obviously your API is out there... it just makes it difficult when conventions on buffer sizes are not followed.

It must even be strange to call it

exif_entry_format_value	(myentry, buf, sizeof(buf)-1);
	
Can it be changed safely?

**Comment by dfandrich** [comment]
The strncpy API is IMHO not a good example to use for good API design. Its
behaviour is broken enough that OpenBSD created strlcpy which does it
sanely. snprintf also uses similar semantics. exif_entry_format_value works
like strlcpy and snprintf. I'm not sure why you say that maxlen doesn't include
the terminating NUL because maxlen is the buffer size which must include the
NUL.

However, it doesn't really make any difference because exif_entry_format_value
is an internal API that can't be used directly by applications. I'm considering
making it public, though, because it can be useful.

**Comment by jonnygrant** [comment]
Fair enough re strncpy. That's why Annex K strncpy_s was introduced

re strlcpy - OpenBSD made it even worse it truncates, breaking strings.
http://technoramauk.blogspot.com/2018/12/strlcpy-considered-harmful.html

C convention is a buffer size, is the total buffer size, which includes space for one NUL terminator.

Quoting again

exif_entry_format_value
val buffer in which to store value
[in] maxlen **one less than the length of the buffer val**

If it is still an internal function, why not consider amending it to follow convention before making it public?

It's just very strange at the moment to need to call with -1  :-

exif_entry_format_value	(myentry, buf, sizeof(buf)-1);

**Comment by dfandrich** [comment]
I suspect you're looking at the 0.6.21 code. exif_entry_format_value hasn't
been that way in a while now.

**Comment by jonnygrant** [comment]
Sounds possible. I was looking at the manual, and you mentioned you only regenerated it this week.

So is maxlen the total buffer size now?

**Comment by dfandrich** [comment]
Do you mean exif_entry_get_value? That's always had those semantics. There is
no guarantee about the parameters to exif_entry_format_value since it's
internal, but that's now it works at the moment, too.

**Comment by jonnygrant** [comment]
I see. exif_entry_get_value() calls exif_entry_get_value(), and neitehr check the 'e' and 'val' pointers are valid BTW

**Comment by dfandrich** [comment]
Good point. There are a handful of functions that are missing NULL checks, mostly on extra pointer parameters. test-null.c is missing those tests.

**Comment by jonnygrant** [comment]
The code all looks very archaic.  Why not use C99 ?
Lots of old macros, better just to use inline functions (compiler will inline them anyway)
Inline functions, get rid of the macros.

snprintf also truncates, better check that.

printf called with %s for a pointer that might be NULL etc

**Comment by jonnygrant** [comment]
Would be better if exif_loader_write_file  returned something that could be checked for status. Probably others similar. exif_loader_write_file just silently returns in cases of errors

**Comment by dfandrich** [comment]
Yup. This is a problem in lots of places in the API and is hard to change in a
backwards-compatible manner.

**Comment by dfandrich** [comment]
Can you guarantee this will never be a problem on every C ABI out there?
For example, it appears that changing the type will lead to undefined behaviour
in programs using pointers to the changed function according to C99:
http://port70.net/~nsz/c/c99/n1256.html#6.5.2.2p9

**Comment by jonnygrant** [comment]
Would your library not be re-compiled for next release? Usually applications are re-compiled, so they would be using your updated header.

Anyway, usually where a legacy API is retained, a new API is added

eg just add:

int exif_loader_write_file2 (ExifLoader *l, const char *path);

Change the old API to be:

/* This API was deprecated, retained for compatibility only
Please update to use exif_loader_write_file2
*/
void
exif_loader_write_file (ExifLoader *l, const char *path)
{
    exif_loader_write_file2(l, path);
}



The whole file contains these problems, eg exif_loader_get_buf() which also doesn't check pointers still.

and exif-entry.c has a lot of possible buffer overruns, eg exif_entry_dump()
and all the macro's #define CC    etc

Sorry to be the barer of bad news.

**Comment by dfandrich** [comment]
Yes, we can change the API and bump the SONAME, but they're both pretty
disruptive and something we don't want to do often.

exif_entry_dump is just a debug function so I'm not too concerned, but if you
know of a buffer overrun elsewhere with a security impact, please open a bug an
SourceForge and mark it as private.

**Comment by jonnygrant** [comment]
Maybe just add exif_loader_write_file2

Sorry I can't review the code base, but you can follow my notes and review functions for similar issues to those I already described.

Re exif_entry_dump, I think debug functions should also not cause crashes.

**Comment by jonnygrant** [comment]
http://spinroot.com/p10/

"Check the return value of non-void functions, and check the validity of function parameters."
Based on: ''The Power of Ten -- Rules for Developing Safety Critical Code,'' IEEE Computer, June 2006, pp. 93-95 (PDF).

**Comment by jonnygrant** [comment]
Would you consider adding GCC attribute __attribute__((nonnull))

 https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html
