### ISSUE TITLE
Process for reporting security bugs

### ISSUE THREAD

**Issue by Google-Autofuzz** [libexif/libexif#2]
Hello Tinyexr,

As part of our fuzzing efforts at Google, we are interested in understanding the process for reporting potential security issues to your project in a private manner. Could you please advise us if there is a private tracker for these kinds of bugs, or if you prefer them filed in a publicly visible way?

Thanks!

**Comment by dfandrich** [comment]
On Tue, Mar 06, 2018 at 07:32:31PM +0000, Google AutoFuzz Team wrote:
> Hello Tinyexr,

I'm not Tinyexr, but pleased to make your acquaintance, anyway!

> As part of our fuzzing efforts at Google, we are interested in understanding
> the process for reporting potential security issues to your project in a
> private manner. Could you please advise us if there is a private tracker for
> these kinds of bugs, or if you prefer them filed in a publicly visible way?

The best way is to open a bug on SourceForge at
https://sourceforge.net/p/libexif/bugs/ and mark it as "private".

**Comment by Google-Autofuzz** [comment]
Perfect, thank you!

I suppose we can't be considered bots anymore :)
