### ISSUE TITLE
undefined behaviour in exif_get_slong

### ISSUE THREAD

**Issue by jcupitt** [libexif/libexif#20]
Hello, thank you for this nice library.

I'm getting a lot of reports of undefined behaviour from ubsan here:

https://github.com/libexif/libexif/blob/master/libexif/exif-utils.c#L137

I see things like:

```
  | exif-utils.c:137:31: runtime error: left shift of 172 by 24 places cannot be represented in type 'int'
  | #0 0x6663a8 in exif_get_slong libexif/libexif/exif-utils.c:0
  | #1 0x6661de in exif_get_rational libexif/libexif/exif-utils.c:192:24
```

I guess you need to cast to `uint32`, then shift, then cast back to `ExifSLong`.

**Comment by msmeissn** [comment]
core issue is ii think

unsigned char b;

b << 24

will implicitly promote to "int" within this expression for C standard weird reasons.

casting to unsigned int helps I think.
