### ISSUE TITLE
undefined behaviour in exif-loader.c

### ISSUE THREAD

**Issue by orangesnn** [libexif/libexif#34]
Hello! The problem of undefined behaviour was found during the OSS Fuzz project test.

Project: libexif
Fuzzer: libFuzzer_libexif_exif_loader_fuzzer
Fuzz target binary: exif_loader_fuzzer
Platform Id: linux
Type of test：undefined

Command:
python infra/helper.py build_fuzzers --sanitizer undefined libexif
python infra/helper.py run_fuzzer libexif exif_loader_fuzzer -max_total_time=300 -timeout=180

Results of execution：
`exif-loader.c :242 27: runtime error: left shift of 255 by 24 places cannot be represented in type 'int'`
`#0 0x4c04d2 in exif_loader_write /src/libexif/libexif/exif-loader.c: 242:27`
`#1 0x4b3d1a in LLVMFuzzerTestOneInput /src/exif_loader_fuzzer.cc 48:3`

The pull request as follows：
[ https://github.com/libexif/libexif/pull/33/commits/3f0f49733b3856144389e460b5ba2409d6d3d08b ](https://github.com/libexif/libexif/pull/33/commits/3f0f49733b3856144389e460b5ba2409d6d3d08b)

**Comment by msmeissn** [comment]
merged, thanks!
