### ISSUE TITLE
Question: Preview on MAC can not read Date Time Original

### ISSUE THREAD

**Issue by alpha-eric** [libexif/libexif#4]
Hi Guys,

We are using libexif to add extra info in our jpg file, but we face some problem I don't know how to fix it. Please help kindly help me. Thanks a lot.

1. Libexif version: cvs-migration

2. My sample code:  [piece.cpp.zip](https://github.com/libexif/libexif/files/2078647/piece.cpp.zip)

3. Following jpg is coming from my sample code. Preview can open it, but can not read Date Time Original.
![41013021-f8bca38c-6976-11e8-9896-e056f5315116](https://user-images.githubusercontent.com/12745424/41073293-35c05ef4-6a35-11e8-8626-e0428898fda6.jpg)

4. I put above jpg into the web site, https://www.thexifer.net/#exif-general.
    Just open it and save it and we got following jpg.
![41013122-3940e1ac-6977-11e8-865c-dfa7d4ac8dc5](https://user-images.githubusercontent.com/12745424/41073360-7ab6548c-6a35-11e8-84bf-5f2f234e49bb.jpg)

5. I use vimdiff to check the diff, only see following diffs.
![vimdiff](https://user-images.githubusercontent.com/12745424/41073430-d79f0b1c-6a35-11e8-86cc-72ca09f2c2b8.png)

6. Question: How do I write the Date Time Original correctly into JPEG and Preview can read it?
Please help. Thanks a lot.

**Comment by dfandrich** [comment]
I haven't looked at the code, but an obvious thin I see looking at the test
image is that the Date and Time field is in the wrong format. The date must use
a colon as a separator, not a dash.

**Comment by alpha-eric** [comment]
Hi @dfandrich 

Thanks. You are right, I use colon and it is correct. Thanks a lot.
![aa](https://user-images.githubusercontent.com/12745424/41084002-7915733a-6a65-11e8-8839-384f37dd3d7a.jpg)
