### ISSUE TITLE
exif_data_get_entry for EXIF_TAG_ORIENTATION returns non-null when orientation field isn't present

### ISSUE THREAD

**Issue by anthonybilinski** [libexif/libexif#46]
When viewing a file with no exit orientation tag present,
```
ExifData* exifData = exif_data_new_from_data(reinterpret_cast<const unsigned char*>(data), size);
const ExifByteOrder byteOrder = exif_data_get_byte_order(exifData);
const ExifEntry* const exifEntry = exif_data_get_entry(exifData, EXIF_TAG_ORIENTATION);
```
returns a non-null `ExifEntry`. From the doxygen docs at https://libexif.github.io/api/exif-data_8h.html#a984540c607eb7cfce58cf34e7374ab47, I'd expect `ExifEntry` to be null if `EXIF_TAG_ORIENTATION` isn't present.

When the orientation is then read with `orientation = exif_get_short(exifEntry->data, byteOrder);`, the returned value is 0, when the valid range for orientation is 1-8 according to exif spec.

Am I misinterpreting the API? Or is it a bug that `exif_get_short` in this case is returning 0 rather than `exif_data_get_entry` returning null?

**Comment by msmeissn** [comment]
hmm, the code in exif-data.h would return NULL if it does not find this tag.

is this the case for all images, or just for some? 

is "exif FOO.JPG" showing Orientation tag?

**Comment by anthonybilinski** [comment]
Sorry looking at this again my report is false and the problem I'm seeing is a bug in our code. `ExifEntry` is correctly null when the field is not present.
