### ISSUE TITLE
add meson build system

### ISSUE THREAD

**Issue by vtorri** [libexif/libexif#56]
Hello

what about adding meson build system ? it would allow also the creation of visual studio and xcode files

thank you

**Comment by vtorri** [comment]
other advantage : a lot faster than autotools.

it has been released in 2013, not sure if it is too recent or not

**Comment by dfandrich** [comment]
I'm against maintaining multiple build systems in parallel, and switching to a
new build system that none of the current contributors are familiar with will
be a hard sell. The advantages would need to outweigh the considerable costs.
And increased build speed IMHO isn't enough.
