### ISSUE TITLE
EXIF not found if APP14 marker appear before APP1

### ISSUE THREAD

**Issue by MarcoMartins86** [libexif/libexif#6]
I have a jpeg file which has an APP14 marker (0xFFEE) before the APP1 marker where libexif does not work since on the exif-loader.c file we can see that APP14 marker is not defined anywhere, I solved this issue by defining it and adding a `case JPEG_MARKER_APP14:` just below the `case JPEG_MARKER_APP13:`

**Comment by ptsneves** [comment]
Is it still working? If yes could you provide a pull request?

**Comment by moho1** [comment]
I ran into the same problem with jpegs generated by ImageMagick convert. In my case it where the APP4 (0xFFE4) and APP11 (0xFFEB) markers located before the APP1 marker, causing libexif not to accept the header. Adding APP4 and APP11 to exif-loader.c, as suggested above, solved it for me.

I can for sure provide a pull request, adding APP4, APP11 and APP14 to the list. But maybe accepting all APP markers (E0-EF, with special regards to APP1) would be a more general solution here? Or would that break compatibility with the exif specifications?

**Comment by chrisg123** [comment]
I also ran into the issue after using ```convert``` from ```ImageMagick``` and faced the following error
```
Corrupt data
The data provided does not follow the specification.
ExifLoader: The data supplied does not seem to contain EXIF data.
```

Using ```exiftool``` I was able to see the the exif data was still there.

After reading the comments from @MarcoMartins86 and @moho1 the following changes to solved my problem:
```
diff --git a/libexif/exif-loader.c b/libexif/exif-loader.c
index f0f0463..fcf025f 100644
--- a/libexif/exif-loader.c
+++ b/libexif/exif-loader.c
@@ -41,6 +41,12 @@
 #define JPEG_MARKER_APP1 0xe1
 #undef JPEG_MARKER_APP2
 #define JPEG_MARKER_APP2 0xe2
+#undef JPEG_MARKER_APP4
+#define JPEG_MARKER_APP4 0xe4
+#undef JPEG_MARKER_APP5
+#define JPEG_MARKER_APP5 0xe5
+#undef JPEG_MARKER_APP11
+#define JPEG_MARKER_APP11 0xeb
 #undef JPEG_MARKER_APP13
 #define JPEG_MARKER_APP13 0xed
 #undef JPEG_MARKER_COM
@@ -285,6 +291,9 @@ exif_loader_write (ExifLoader *eld, unsigned char *buf, unsigned int len)
                        case JPEG_MARKER_DQT:
                        case JPEG_MARKER_APP0:
                        case JPEG_MARKER_APP2:
+                       case JPEG_MARKER_APP4:
+                       case JPEG_MARKER_APP5:
+                       case JPEG_MARKER_APP11:
                        case JPEG_MARKER_APP13:
                        case JPEG_MARKER_COM:
                                eld->data_format = EL_DATA_FORMAT_JPEG;
```

This may only solve the problem for my particular usage of ```ImageMagick 7.0.11-3```'s ```convert``` but I can submit as a pull request if this is suitable as an "incremental fix". 

I can also add the marker for ```APP14``` to solve @MarcoMartins86 issue though I don't have an image to test it with.

Not sure of the ramifications of adding these markers but I would think the use of ```convert``` would be relatively common.

**Comment by msmeissn** [comment]
I added all the 4 markers to libexif git now.
