### ISSUE TITLE
configure.ac:206: error: `po/Makefile.in' is already registered with AC_CONFIG_FILES.

### ISSUE THREAD

**Issue by chrisg123** [libexif/libexif#60]
The following sequence of events is giving an error when trying to compile.

```
git clone https://github.com/libexif/libexif
cd libexif
gettextize
mv po/Makevars.template po/Makevars
aclocal -I auto-m4
```
**Result:**
```
configure.ac:206: error: `po/Makefile.in' is already registered with AC_CONFIG_FILES.
../../lib/autoconf/status.m4:288: AC_CONFIG_FILES is expanded from...
configure.ac:206: the top level
autom4te-2.69: /usr/bin/m4 failed with exit status: 1
aclocal-1.16: error: echo failed with exit status: 1
```
**What works:**
I notice that if I run ```git reset --hard``` before running  ```aclocal -i auto-m4``` it solves the issue.

I did run into another issue when running ./configure:
```
./configure: line 2860: GP_CHECK_SHELL_ENVIRONMENT: command not found
./configure: line 2861: syntax error near unexpected token `Build'
./configure: line 2861: `GP_CONFIG_MSG(Build)'
```
to solve this I had to append ```-I m4m``` to the ```aclocal``` command.

So a successful compile required me to do the following:
```
git clone https://github.com/libexif/libexif
cd libexif
gettextize
mv po/Makevars.template po/Makevars
git reset --hard
aclocal -I auto-m4 -I m4m
autoheader
libtoolize --force
automake --add-missing
autoconf
./configure
make
```
My issues arose while following the instructions in the ```README``` file. I am happy to submit a pull request with updates to the ```README``` if anything I did makes sense. Not sure why the ```git reset --hard``` was needed after running ```gettextize``` and copying the ```Makevars.template``` file.

**Sytem info**
```
Gentoo Linux 5.4.80
autoconf (GNU Autoconf) 2.69
automake (GNU automake) 1.16.2
```

**Comment by dfandrich** [comment]
Do the autoreconf version of the instructions work?

**Comment by chrisg123** [comment]
> Do the autoreconf version of the instructions work?

... yes... didn't even get that far down the instruction... 

the ```When building from source out of git, something like the following will be
necessary: ...``` instructions threw me off.

**Comment by misieck** [comment]
Got this very error right now. I tried run autogen.sh, failed first because of missing autopoint, installed autopoint and rerun autogen. Resulting in above message. `git reset --hard` is a workaround. This feels like automake is showing its age - not very robust.

**Comment by ndim** [comment]
Where did you find the `autogen.sh` command you are running? I thought we had removed that.

**Comment by misieck** [comment]
@ndim Oh, damn, ooks like I posted in the wrong project. I wasn't building libexif. My bad.
