### ISSUE TITLE
update configure.ac

### ISSUE THREAD

**Issue by vtorri** [libexif/libexif#63]
Here is a patch which updates configure.ac

[0001-update-configure.ac.txt](https://github.com/libexif/libexif/files/6322593/0001-update-configure.ac.txt)

**Comment by dfandrich** [comment]
What is the purpose of the patch?

**Comment by vtorri** [comment]
as stated in the patch : 

* use LT_INIT instead of old libtool macro
* add xz tarbal when running make dist
* remove obsolescent macros

**Comment by ndim** [comment]
Is `dist-xz` even supported with the required automake version of 1.9? As the libexif `configure.ac` file stands right now (and which is not changed by the proposed patch), it requires `autoconf >= 2.59` (released 2003-11-06) and `automake >= 1.9` (released 2004-07-28). `dist-xz` was first added to automake in 2008-11, so automake-1.9 cannot recognize `dist-xz`.

So while touching the build system, I would increase the tool version requirements, to at least `autoconf >= 2.62` and `automake >= 1.10.1` (released in 2008-04 and 2008-01, respectively). Or even better yet, `autoconf >= 2.69` and `automake >= 1.12` (released in 2012-04-25). That might also allow cutting off some compat issues the ~18 year old toolset generation tends to add over the ~9 year old toolset generation.

Macros and `configure.ac` files written properly for `autoconf >= 2.69` should also be compatible with the most recent `autoconf-2.71` (from 2021-01), which I would not expect every works-with-autoconf-2.59 `configure.ac` to be compatible with.

**Comment by vtorri** [comment]
i can add a PR with my changes and autoconf >= 2.69 and automake >= 1.12 , if you agree

**Comment by hughmcmaster** [comment]
@vtorri, any progress on this? The proposed versions of autoconf and automake have been around forever, so this is a non-issue.

**Comment by vtorri** [comment]
here it is : #65

**Comment by ndim** [comment]
Thanks for the input, I have just squashed your changes and pushed them.

Unfortunately, I forgot to add the appropriate comments, so I need to close this manually.
