### ISSUE TITLE
Problems reading JFIF version 1.02

### ISSUE THREAD

**Issue by chriamue** [libexif/libexif#67]
Hi,
when I convert a JPEG file using [img-parts](https://github.com/paolobarbolini/img-parts)
I cannot read the file using exif, which reports the file is corrupt.

I already reported an [Issue](https://github.com/paolobarbolini/img-parts/issues/2) in the img-parts repo, but I think it could fit here, because
I can still print the exif data with ```exiftool``` and ```identify```.

Here is a diff of exiftool output from the origin (which is readable by exif) and the converted image:

```
img-parts/examples/image-rs$ exiftool IMG_0818.JPG > img.txt
img-parts/examples/image-rs$ exiftool out.jpg > out.txt
img-parts/examples/image-rs$ diff img.txt out.txt
2c2
< File Name                       : IMG_0818.JPG
---
> File Name                       : out.jpg
4,7c4,7
< File Size                       : 5.9 MB
< File Modification Date/Time     : 2021:05:26 12:16:06+02:00
< File Access Date/Time           : 2021:05:26 12:16:42+02:00
< File Inode Change Date/Time     : 2021:05:26 12:16:06+02:00
---
> File Size                       : 36 kB
> File Modification Date/Time     : 2021:05:26 12:17:27+02:00
> File Access Date/Time           : 2021:05:26 12:18:16+02:00
> File Inode Change Date/Time     : 2021:05:26 12:17:27+02:00
11a12,18
> JFIF Version                    : 1.02
> Image Width                     : 256
> Image Height                    : 170
> Encoding Process                : Baseline DCT, Huffman coding
> Bits Per Sample                 : 8
> Color Components                : 3
> Y Cb Cr Sub Sampling            : YCbCr4:4:4 (1 1)
286c293
< Thumbnail Offset                : 10936
---
> Thumbnail Offset                : 11042
288,294d294
< Rating                          : 0
< Image Width                     : 5184
< Image Height                    : 3456
< Encoding Process                : Baseline DCT, Huffman coding
< Bits Per Sample                 : 8
< Color Components                : 3
< Y Cb Cr Sub Sampling            : YCbCr4:2:2 (2 1)
302c302
< Image Size                      : 5184x3456
---
> Image Size                      : 256x170
304c304
< Megapixels                      : 17.9
---
> Megapixels                      : 0.044
```

The JFIF Version Tag was added but nothing special.

Here is the converted image:
![large](https://user-images.githubusercontent.com/7541795/119705452-0cbcd200-be59-11eb-90ac-2c0b9a639316.jpg)

The origin image is
[here](https://user-images.githubusercontent.com/7541795/119443336-bc932200-bd29-11eb-94bf-0fc4b6aea471.JPG)

**Comment by dfandrich** [comment]
libexif assumes that the input is a valid file. For the most part, it won't try
to second-guess what a corrupted file should really be. I haven't tried to
figure out exactly how that file is corrupted, but image viewing programs I've
tried show it as truncated. GIGO.

**Comment by msmeissn** [comment]
The issue here is that there are is an APP1 Marker at the begin with some kind of Adobe tag and later on there is ANOTHER APP1 Marker with EXIF Data.

We only look for the first APP1 marker currently.

**Comment by msmeissn** [comment]
actually different... 
ff d8
ff e1 - some adobe marker
ff db - DQT
ff c0 - Baseline DCT
ff e1 - APP1 with EXiF

Usuaully EXIF should appear BEFORE the actual image data.

**Comment by msmeissn** [comment]
i skip over 0xc0 now too, seems to report EXIF now.

**Comment by chriamue** [comment]
Thank you both for the quick response. I tested master branch and it works for me now.
As I understand there is space for improvement as the order of DCT and APP1 is not the way it should be.
I will take this as homework and try to find a solution with the author of https://github.com/paolobarbolini/img-parts (@paolobarbolini).
