### ISSUE TITLE
How to compile and run the code so that debugging becomes a possibility?

### ISSUE THREAD

**Issue by Joride** [libexif/libexif#82]
Question: How can I compile and run the code without `configure` and `make` so that debugging becomes a possibility?

More context:
I feel a bit lost. I am now able to [build the library](https://github.com/libexif/libexif/issues/80#issuecomment-980635083) and use it in an iOS application.
I would like to also contribute to the project itself, and for that I would like to be able to debug the code (breakpoints, step-through etc). Since this is a C project I tried compiling the all .c-files from the command line directly. 

However, finding the commands that are executed by `make` and how make creates or changes source files is beyond me. For instance, when building the library using `make install`, the resulting `include' folder contains a file `_stdint.h` that I can't find in the cloned repository (even after running `autoreconf -i` and the iOS-specific `./configure` script linked to at the beginning of this post). `GETTEXT_PACKAGE`  is in a number of source files, but can't be resolved (does make do some preprocessing?)

So now I feel a bit out of options / at the outer limits of my knowledge, and I hope someone can tell me how to be able to debug?

**Comment by dfandrich** [comment]
Why do you want to run it without configure? As you surmise, that would be a
difficult task, and definitely not one for a beginner. Just the configure source
itself contains over 2400 CLOC, which is a lot of information that you'd have
to use to duplicate what it's doing another way, such as manually.

How do you normally build for iOS? I would expect on a Mac, which is perfectly
capable of running configure. The README file contains instructions for
building libexif for the build host, but cross-compiling, which is what you'd
do for iOS, is only slightly different. I'm not personally familiar with
compiling to iOS, but it may be as simple as using a configure command
like: ./configure --host=arm64-apple-ios  I'm sure you can find a tutorial on
cross-compiling to iOS using autoconf.

Alternately, you can just follow the instructions for building for the local
host but rather than running "make" run "make -n V=1". That will display all
the commands that would be run without actually running them. You could then
try adapting them to your situation, but I suggest not bothering trying to do
this.

**Comment by Joride** [comment]
I want to be able to run the code _and_ debug it: place breakpoints in the source and step through it, inspect variables at runtime etc.
I don't know how to be able to run and debug the code using configure/make. If that is possible using configure/make, I would like to learn how.
Usually I use Xcode when building an application or library. But when code us using configure/make, Xcode will set the project up in a so-called 'external build', meaning it will simply run `make` to do the building, but it won't have the ability to attach a debugger (or it can, but I don't know how).

**Comment by Joride** [comment]
Well now that I am writing it out like this, I think I am halfway towards answering my own question. Some googling shows that it is a matter of setting up Xcode with an 'external build system', adjusting some settings, and making sure the right arguments are passed to `configre`. Going to look into it.

**Comment by Joride** [comment]
Ok, I was able to get this working through Xcode. I wrote down what I did for my future self, but will share here so others might benefit to.

2 issues remain:
- building for platforms other than iphoneos, such as iphonesimulatorOS
- building with bitcode enabled

```
Here is how is got building and debugging working:

# Requirements
- a mac computer
- autotools:
> `brew install autoconf automake libtool`
- xcode 13.0

- ios specific configure script
https://gist.github.com/Joride/19da3b871a3d6ff9bbea15a977740d5c

# Preparing files and directories
1. create container folder, inside it, create a new folder called `app`. Create a new Xcode project in this folder.
2. inside that container folder, run:
> `git clone https://github.com/libexif/libexif.git`

The directory structure now should look like this:
- <container dir>
| - (dir) app
|    | - (dir) <application name>
|    |   | - (dir) <application name>    
|    |   | - (file) <application name>.xcodeproj ! This one is actually a bundle, not a file
| - (dir) libexif
|    | - README
|    | - AUTHORS
|    | - ...
| - (file) configure-libexif-foriOS.sh

# Preparing the exiflib project
Open `configure-foriOS.sh` and change the hardcoded paths at the top of the file
to be what you want.  
I recommend as a target directory (where the `libexif.a` and `inlude` folder will end up to be a directory wiht the name indicating the platform it was built for and to place it inside the 'app' directory, so it will be picked up by git and included).
! Verify that the xcode paths are correct (sometimes you might have multiple versions of xcode installed and change the default, `Xcode` to something like 'Xcode13.0') 
in terminal: `cd` into the container dir and run:
`./configure-foriOS.sh`
This script sets a number of variables, and then runs:

> `autoreconf -i`
> `configure ...`
> `make install` 
If all is well, there should now be a new directory with a 'lib', 'include' and 'share' folder in your target directory. If not, well, double check everything. Good luck.

The directory structure now should look like this (assuming `libexif-iPhoneOS` is the name of the target dir)
- <container dir>
| - (dir) app
|    | - (dir) <application name>
|    |   | - (dir) <application name>    
|    |   | - (file) <application name>.xcodeproj ! This one is actually a bundle, not a file
|    |   | - (dir) libexif-iPhoneOS
|    |   |   | - (dir) include
|    |   |   | - (dir) lib
|    |   |   | - (dir) share
| - (dir) libexif
|    | - README
|    | - AUTHORS
|    | - ...
| - (file) configure-libexif-foriOS.sh

# 1-time Xcode configuration to enable using libexif
## setup building libexif
- add a new target to to the project. Choose 'external build system'
- select the target, and select the tab 'Info'. Change the field 'Arguments' to contain:
> `-j8 install` 
'-j8' is for a machine with 8 cores (in this case an M1 Macbook Air)
- change the directory to the libexif directory in the container directory.
- keep 'Pass build settings in environment' selected
## setup including libexif into the application
- in xcode, select the application target
- select 'Build Phases' and unfold 'Dependencies'. Click the '+' and add the external build tool target
- in 'Link Binary With Libraries', click the plus and add the `libexif.a` file from the target directory. You might need to manually find it by choosing 'other'.
- Select the tab 'Build Settings'. Update the 'Header Search Paths' to contain the path to the 'include' folder created when the configure script was run


# Repeated Xcode configuration to enable debuggin libexif
-  all the files from libexif's `libexif` folder (the folder that contains all the .c files) should be part of the project. When dragging these into the project, make sure to select **create groups**, and **not** create folder references.
- Now you can set breakpoints here
- When pulling new code from libexif, add any new source files to the project. This is the one step that I could not find how to automate.

# Building different architectures, debug or optimized binaries
- In the configure script, one of the CFLAGS is '-g'. This option will make the binarydebuggable. It should not be there for release builds.
```

**Comment by Joride** [comment]
One more update. A complete workflow to incorporate and debug libexif can be achieved using Xcode13 or Xcode 13.1 (maybe previous or later versions too, but these are the ones I have available now).

I wrote a manual and uploaded that together with the necessary scripts to a new repo in my github account:
[https://github.com/Joride/Autotools-Xcode](https://github.com/Joride/Autotools-Xcode)
