### ISSUE TITLE
LIBEXIF_REVISION has not increased for 0.6.2[34]

### ISSUE THREAD

**Issue by sreschke80** [libexif/libexif#84]
Just as a remark for you.
When integrating the last release of libexif I wondered, that the generated library still uses the same name.
libexif.so.12.3.4
After a bit of research I found that `LIBEXIF_REVISION` in configure.ac was not changed for the releases 0.6.23 and 0.6.24.
If it is intended please close this issue.
Regards
Sebastian

**Comment by msmeissn** [comment]
if we do not add new interfaces this is not strictly required though.
