### ISSUE TITLE
Accessing out of the range of the allocated memory.

### ISSUE THREAD

**Issue by KonstantinBYvitebsk** [libexif/libexif#87]
https://github.com/libexif/libexif/blob/b77f10a1be383604cd337b9bc10f9e205c5ad94c/contrib/c%2B%2B/exif_module.cxx#L156

Here is trying accessing out of the range allocated memory.

**Comment by msmeissn** [comment]
i cant even get it to build. But I will change it to size-1

**Comment by KonstantinBYvitebsk** [comment]
I think it will be better to do one of the options:

Jsut delete setting '0'. Delete this line.
Alloc not malloc(entry_->size); but malloc(entry_->size + 1);
Use another way to alloc. for example: strbup .But I am not sure about portability.

**Comment by msmeissn** [comment]
strdup might not work, as data might not be \0 terminated.
i changed it to +1 and calloc now.
