### ISSUE TITLE
Permission to use the test images for closer integration

### ISSUE THREAD

**Issue by ashwani-rathee** [libexif/libexif#88]
Hey @dfandrich @msmeissn @ndim, I wanted to ask for your permissions to use the test images in test/testdata for the package I was working on here:
https://github.com/ashwani-rathee/ExifViewer.jl

ExifViewer.jl is a wrapper over libexif which provides LibExif functionalities to Julian World. I would be more than happy to add links back to libexif repository and mention about the libexif project more.

**Comment by dfandrich** [comment]
The images are available under the same license as the rest of libexif, so feel
free to use them in the same way!

**Comment by ashwani-rathee** [comment]
Thank you so much!!
